[project]
name = "python"
version = "0.1.0"
description = "awakelion websocket python logging server here."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eventlet>=0.40.3",
    "flask>=3.1.2",
    "flask-socketio>=5.5.1",
]
